# Generated by Django 4.2.16 on 2024-11-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0040_alter_game_game_type_value_and_more'),
        ('bingosync', '0045_makeplayerrefereeevent'),
    ]

    operations = [
    ]
